name: fwitter_server
description: Starting point for a Serverpod server.
# version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  fwitter_shared:
    path: ../fwitter_shared
  serverpod: 2.0.0
  serverpod_auth_server: 2.0.0

dev_dependencies:
  build_runner: ^2.4.9
  lints: ^3.0.0
  mockito: ^5.4.4
  test: ^1.25.2
