name: fwitter_client
description: Starting point for a Serverpod client.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  fwitter_shared:
    path: ../fwitter_shared
  serverpod_auth_client: 2.0.0
  serverpod_client: 2.0.0
