name: fwitter_flutter
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  fwitter_shared:
    path: ../fwitter_shared
  bloc: ^8.1.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.1
  fwitter_client:
    path: ../fwitter_client
  get_it: ^7.6.7
  injectable: ^2.3.5
  intl: ^0.18.1
  serverpod_auth_email_flutter: 2.0.0
  serverpod_auth_shared_flutter: 2.0.0
  serverpod_flutter: 2.0.0

dev_dependencies:
  bloc_test: ^9.1.6
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  freezed: ^2.5.0
  injectable_generator: ^2.5.1
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
